# 1.Data structure

Cho một dictionary gồm tên và điểm số <br>
`points = {'an':9, 'bình': 7, 'khanh':8, 'linh':10, 'huyen':6}`<br>
1. Hãy sắp xếp dictionary trên theo điểm số tăng dần.

In [11]:
points = {'an':9, 'bình': 7, 'khanh':8, 'linh':10, 'huyen':6}
sorted(points.items(), key=lambda item: item[1],reverse=True)

[('linh', 10), ('an', 9), ('khanh', 8), ('bình', 7), ('huyen', 6)]

2. Hãy tạo một dictionary có key là điểm số và giá trị là tên.

In [7]:
new_points = dict((value, key) for key, value in points.items())
new_points

{9: 'an', 7: 'bình', 8: 'khanh', 10: 'linh', 6: 'huyen'}

Tiếp theo, cho một list như sau:<br>
`target = ['vi', 'mot', 'cong', 'dong', 'AI', 'vung', 'vung', 'manh', 'manh', 'hon']`<br>
3. Tìm các giá trị duy nhất của list đó

In [13]:
#Method 1
target = ['vi', 'mot', 'cong', 'dong', 'AI', 'vung', 'vung', 'manh', 'manh', 'hon']
new_target = []
for word in target:
    if word not in new_target:
        new_target.append(word)
print(new_target)

new_target2 = set(target)
new_target2 = list(new_target2)
print(new_target2)

['vi', 'mot', 'cong', 'dong', 'AI', 'vung', 'manh', 'hon']
['hon', 'manh', 'mot', 'AI', 'cong', 'vi', 'vung', 'dong']


4. Đếm số lần lặp lại của một phần tử trong list

In [18]:
#Method 1
count = {}
for k in target:
    if k not in count.keys():
        count[k] = 1
    else:
        count[k] += 1
print(f'Method 1: \n {count}')

#Method 2 using comprehention and function count
countDict = {element: target.count(element) for element in target}
print(f'Method 2: \n {countDict}')

#Method 3 using function Counter in package collections
from collections import Counter
countDict = Counter(target)
print(f'Method 3: \n {countDict}')



Method 1: 
 {'vi': 1, 'mot': 1, 'cong': 1, 'dong': 1, 'AI': 1, 'vung': 2, 'manh': 2, 'hon': 1}
Method 2: 
 {'vi': 1, 'mot': 1, 'cong': 1, 'dong': 1, 'AI': 1, 'vung': 2, 'manh': 2, 'hon': 1}
Method 3: 
 Counter({'vung': 2, 'manh': 2, 'vi': 1, 'mot': 1, 'cong': 1, 'dong': 1, 'AI': 1, 'hon': 1})


5. Tạo ra một list mới mà nếu phần tử đố đã xuất hiện trong list rồi thì chỉ lấy duy nhất giá trị bắt gặp đầu tiên


In [20]:
nunique_list = []
for word in target:
    if word not in nunique_list:
        nunique_list.append(word)
print(nunique_list)

['vi', 'mot', 'cong', 'dong', 'AI', 'vung', 'manh', 'hon']


Cho một đoạn văn bản như sau:<br>
`words = 'Machine Learning Algorithms to Practice là một cuốn sách cân bằng giữa lý thuyết và thực hành'`<br>

6. Hãy phân chia câu văn trên thành một  list mà mỗi một từ trong cầu là một phần tử của list

In [22]:
words = 'Machine Learning Algorithms to Practice là một cuốn sách cân bằng giữa lý thuyết và thực hành'

lst_words = words.split()
print(lst_words)

['Machine', 'Learning', 'Algorithms', 'to', 'Practice', 'là', 'một', 'cuốn', 'sách', 'cân', 'bằng', 'giữa', 'lý', 'thuyết', 'và', 'thực', 'hành']


7. Đảo ngược vị trí các từ trongg list vừa tạo được

In [23]:
reverse_lst = lst_words[::-1]
print(reverse_lst)

['hành', 'thực', 'và', 'thuyết', 'lý', 'giữa', 'bằng', 'cân', 'sách', 'cuốn', 'một', 'là', 'Practice', 'to', 'Algorithms', 'Learning', 'Machine']


8. Tính giai thừa $n!=1 \times 2 \times 3...\times n$

In [29]:
#Method 1 using for
def fractorial(n):
    frac = 1
    for i in range(2, n+1):
        frac *= i
    return frac


In [30]:
fractorial(20)

2432902008176640000

In [26]:
#Method 2 using while
def fractorial(n):
    frac = 1
    value = 1
    while value <= n:
        frac *= value
        value += 1
    return frac

In [27]:
fractorial(20)

2432902008176640000

9. Tích của số chắn liên tiếp khác 0 nhỏ hơn n

In [33]:
#Method 1 Using for
def pro_even_1(n):
    mul = 1
    for i in range(2, n+1, 2):
        mul *= i
    return mul

In [37]:
pro_even_1(20)

3715891200

In [42]:
#Method 2 using while
def pro_even_2(n):
    mul = 1
    step = 2
    while step <=n:
        mul *= step
        step += 2
    return mul

In [43]:
pro_even_2(20)

3715891200

10. Viết một chương trình dự đoán chữ số may mắn với user story như sau:
- Lấy thông tin `name` của người chơi và xuất ra màn hình: `welcome your_name to the digit guessing game`.
- Sử dụng hàm random để tạo một **chữ số may mắn** ngẫu nhiên. 
- Chương trình cho phép người chơi nhập tối đa 5 lượt. Nếu người chơi nhập vào một chữ số :
  - trùng với chữ số may mắn thì in ra `congratulate you are a winner`, in ra tổng số lượt đã dự đoán và kết thúc trò chơi.
  - lớn hơn chữ số may mắn thì in ra gợi ý `you should guess le

In [47]:
#Method 1 using While
import random
random.seed(42)

def guessNumberWhile(lb=0, ub = 9, nGuess=5):
    """
    Args:
        lb: lower bound for random number
        ub: upper bound for random number
        nGuess: the maximum number for guesses
    """
    name = input('Your name')
    print(f'Welcome {name} to the digit guessing game')
    
    randN = random.randint(lb, ub)
    isEnd = False
    total_guess = 0

    while not isEnd:
        number = int(input('You choose number: '))
        total_guess += 1

        if number == randN:
            print('Congratulate you are a winner')
            print('You guessed total ' + str(total_guess) + ' times')
            isEnd = True
        elif number > randN:
            print('You should guess less\n')
        else:
            print('You should guess more')
        
        if total_guess > 5:
            print('You losser')
            break
guessNumberWhile()

Welcome Tuan to the digit guessing game
You should guess more

You should guess more

You should guess more

You should guess more

You should guess more

You should guess more

You losser


In [50]:
def guessNumberFor(lb=0, up=9, nGuess=5):
    '''
    Args:
        lb: lower bound for random number
        up: upper bound for random number
        nGuess: the maximum number of guesses
    '''
    name = input('Your name')
    print(f'Welcome {name} to the digital guessing game')
    randN = random.randint(lb, up)

    for total_guess in range(nGuess):
        number = int(input('You choose number: '))
        if number == randN:
            print('Congratulate you are a winner')
            print('You guessed total ' + str(total_guess) + ' times')
            break
        elif number < randN:
            print('You should guess more\n')
        else:
            print('You should guess less\n')

guessNumberFor()


Welcome Tuan to the digital guessing game
You should guess less

You should guess less

You should guess less

Congratulate you are a winner
You guessed total 3 times


# 2. Numpy

In [51]:
import numpy as np

Cho ma trận $\mathbf{A}$

In [74]:
A = np.array([[10, 1, 2],
              [9, 7, 4],
              [0, 2, 1]])

B = np.array([[2, 3, 4],
              [0, 4, 2],
              [3, 2, 1]])

11. concatenate ma trận $\mathbf{A}$ và ma trận $\mathbf{B}$ theo dòng

In [55]:
#Concate row
C = np.concatenate((A, B), axis=1)
C

array([[10,  1,  2,  2,  3,  4],
       [ 9,  7,  4,  0,  4,  2],
       [ 0,  2,  1,  3,  2,  1]])

12. concatenate ma trận $\mathbf{A}$ và ma trận $\mathbf{B}$ theo cột

In [57]:
#Concatenate columns
D = np.concatenate((A, B), axis=0)
D

array([[10,  1,  2],
       [ 9,  7,  4],
       [ 0,  2,  1],
       [ 2,  3,  4],
       [ 0,  4,  2],
       [ 3,  2,  1]])

13. Mở rộng thêm một chiều ở vị trí số 0 và concatenate ma trận $\mathbf{A}$ và ma trận $\mathbf{B}$ theo chiều mới mở rộng(tức ra kết quả thu được là 1 tensor 3D có nội dung là một list gồm 2 ma trận $\mathbf{A}$ và $\mathbf{B}$)

In [59]:
tensorA = np.expand_dims(A, axis=0)
tensorB = np.expand_dims(B, axis=0)

np.concatenate((tensorA, tensorB), axis=0)

array([[[10,  1,  2],
        [ 9,  7,  4],
        [ 0,  2,  1]],

       [[ 2,  3,  4],
        [ 0,  4,  2],
        [ 3,  2,  1]]])

14. Tính ma trận maximum của ma trận A và B mà mỗi phần tử $m_{ij}$ của nó (phần tử thuộc dòng thứ i cột thứ j) có giá trị bằng maximum của phần tử $a_{ij}$ và $b_{ij}$ tương ứng

In [60]:
np.maximum(A, B)

array([[10,  3,  4],
       [ 9,  7,  4],
       [ 3,  2,  1]])

15. Reshape ma trận $\mathbf{B}$ thành vector

In [62]:
np.reshape(B, -1)

array([2, 3, 4, 0, 4, 2, 3, 2, 1])

Tính toán<br>
16. Tính ma trận phân phối xác xuất C sau khi biến đổi các véc tơ dòng của ma trận $\mathbf{A}$ theo hàm softmax

In [63]:
A

array([[10,  1,  2],
       [ 9,  7,  4],
       [ 0,  2,  1]])

In [65]:
np.sum(A, axis=0)

array([19, 10,  7])

In [69]:
softmax_A = np.exp(A)
softmax_A = softmax_A / softmax_A.sum(axis=1, keepdims=True) # sum for row
softmax_A

array([[9.99541338e-01, 1.23353201e-04, 3.35308764e-04],
       [8.75600595e-01, 1.18499655e-01, 5.89975040e-03],
       [9.00305732e-02, 6.65240956e-01, 2.44728471e-01]])

17. Tìm ra nhãn dự báo cho mỗi dòng ma trân softmax_A

In [70]:
np.argmax(softmax_A, axis=1)

array([0, 0, 1], dtype=int64)

18. Tìm mean, min, max của mỗi dòng ma trận C

In [71]:
print('Min for row: ',np.min(softmax_A, axis=1))
print('Max for row: ',np.max(softmax_A, axis=1))
print('Mean for row: ',np.mean(softmax_A, axis=1))

Min for row:  [0.00012335 0.00589975 0.09003057]
Max for row:  [0.99954134 0.8756006  0.66524096]
Mean for row:  [0.33333333 0.33333333 0.33333333]


19. Biến đổi các dòng của ma trận $\mathbf{A}$ bằng cách trừ đi giá trị nhỏ nhất của mỗi dòng để thu được ma trận $\mathbf{D}$

In [82]:
A

array([[10,  1,  2],
       [ 9,  7,  4],
       [ 0,  2,  1]])

In [84]:
D = A - np.min(A, axis=1, keepdims=True)
D

array([[9, 0, 1],
       [5, 3, 0],
       [0, 2, 1]])

20. Tình toán lại phân phối xác suất của mỗi dòng trên ma trận $\mathbf{D}$ và nhận xét về kết quả nhận được so với phân phối xác suất nhận được từ câu 14.

In [85]:
D = np.exp(A)
D = D / np.sum(D, axis=1, keepdims=True)
D

array([[9.99541338e-01, 1.23353201e-04, 3.35308764e-04],
       [8.75600595e-01, 1.18499655e-01, 5.89975040e-03],
       [9.00305732e-02, 6.65240956e-01, 2.44728471e-01]])

In [86]:
np.argmax(D, axis=1)

array([0, 0, 1], dtype=int64)

21. Tạo thành ma trận con kích thước `2x2` bằng cách trích xuất 2 dòng đầu tiên và 2 cột đầu tiên của ma trận $\mathbf{A}$

In [89]:
subA = A[:2, :2]
subA

array([[10,  1],
       [ 9,  7]])